// Code generated by genregistry. DO NOT EDIT.

package routes

// FunctionRegistry maps function names to their implementations
var FunctionRegistry = map[string]interface{}{
	"QueryTodos":     queryTodos,
	"FormCreateTodo": formCreateTodo,
}
